# Generated by Django 3.1.1 on 2020-09-17 13:37

from django.db import migrations
import imagekit.models.fields
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200915_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='picture',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to=post.models.post_image_path),
            preserve_default=False,
        ),
    ]
