# Generated by Django 3.1.1 on 2020-09-17 13:01

from django.db import migrations
import imagekit.models.fields
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200917_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='profile/default.png', null=True, upload_to=user.models.post_image_path),
        ),
    ]
