# Generated by Django 3.1.1 on 2020-09-30 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200930_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='user_id',
            new_name='user_from',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='following_user_id',
            new_name='user_to',
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('user_from', 'user_to')},
        ),
    ]
