# Generated by Django 3.1.1 on 2020-09-18 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0006_auto_20200918_1026'),
        ('comment', '0003_remove_comment_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like_count',
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='comment_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='post.post'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
